### ISSUE TITLE
Allow using env vars in config env values

### ISSUE THREAD

**Issue by Nekroze** [Nekroze/dab#266]
### Please describe the current behaviour

At present dab only allows static env var values defined in the configuration.

### What is suboptimal about the current behaviour

The current behaviour is insufficient because it is too static.

### Describe the way you think it should behave

Support env substitution when loading envs from configuration.

**Comment by tom-schumann** [comment]
See https://github.com/tom-schumann/dab/commit/3475b5ca654691865f86fed909020aaa6adfa84f

**Comment by Nekroze** [comment]
@tom-schumann awesome! Could you open a pull request for this so we can run it through CI and discuss?
