### ISSUE TITLE
Ansible + Docker host integration

### ISSUE THREAD

**Issue by nickgerman** [Nekroze/dab#305]
### Please describe the current behaviour

The ansible dab container can run ansible commands but cannot orchestrate docker containers on the host.

### What is suboptimal about the current behaviour

The current behaviour is insufficient because ansible can be used to orchestrate containers and therefore should be able to orchestrate docker containers on the host via the docker socket

### Describe the way you think it should behave

The ansible container should be able to execute vanilla docker commands + ansible docker plugin commands to be executed on the docker host (not inside the ansible dab container)

**Comment by Nekroze** [comment]
Thank you for lodging this change request, as I understand it this is a common use of case Ansible and thus should be supported out of the box so to speak.

Sounds like we need to ensure the requirements for the Ansible docker module are installed in the dockerized Ansible app Dab provides and that it mounts the docker socket for full access to docker on the host.

**Comment by Nekroze** [comment]
https://github.com/Nekroze/dab/blob/master/app/docker/Dockerfile.ansible shows that docker-py is already installed however by default it runs without the docker group access and does not mount `docker.sock`. should be a simple change.
