### ISSUE TITLE
Split repo list fetching functionality to repo report

### ISSUE THREAD

**Issue by Nekroze** [Nekroze/dab#319]
### Please describe the current behaviour

At present `dab repo list` fetches all repos that have been cloned and lists statuses for all repos cloned or not. 

### What is suboptimal about the current behaviour

The current behaviour is insufficient because the list can become quite long and it can take quite some time to fetch all repos just to see the available repos.

### Describe the way you think it should behave

New subcommand `dab repo report` can do the fetching of all repos, then run `dab repo list` and filter out the repos that are not cloned. This should live `dab repo list` as faster operation to view all repos dab knows about and the report can be used more to ensure your repos are up to date and such or perhaps only the report should show the boolean statuses.

**Comment by patrickgordon** [comment]
So list would remain the same and report would apply a filter to the output of list?

**Comment by Nekroze** [comment]
Pretty much but I think maybe removing the fetch on each repo to the report subcommand but if we do that then maybe the ticks and crosses of `dab repo list` would be less clear, at least to existing users so perhaps the report subcommand could decorate the `repo list` output with the clean and uptodate columns rather than have them in both. At least that was my thoughts after our discussion.

**Comment by Nekroze** [comment]
#321 is in a similar space
