### ISSUE TITLE
Periodic stable PR

### ISSUE THREAD

**Issue by Nekroze** [Nekroze/dab#328]
### Is your feature request related to a problem? Please describe

Tried to merge #327 from `master` to `stable` branch after a busy week of changes and there was a merge conflict requiring a force push that should not be repeated next time.

### Describe the solution you'd like

On a regular interval a PR from `master` to `stable` should be opened for review and acceptance by stake holders.

### Describe alternatives you've considered

Manually doing it when desired however due to the risk of merge conflicts accruing over time this will not work.

**Comment by Nekroze** [comment]
not sure how to tackle this, maybe something like [hub](https://hub.github.com/) using the @Rozebot account and a [scheduled circle ci workflow](https://circleci.com/docs/2.0/workflows/)...

**Comment by Lachlan-S** [comment]
This [stackoverflow](https://stackoverflow.com/questions/15302570/automatically-open-a-pull-request-on-github-by-command-linel) link show creating a pull request using `hub` that could work.

**Comment by Nekroze** [comment]
Maybe using straight up curl will suffice, https://developer.github.com/v3/auth/#via-oauth-tokens shows how to authenticate correctly and another answer from the stackoverflow @Lachlan-S linked is currently telling me there are no changes between the branches which is correct.

I think this will be better as we can automatically have it close any old PR's it has opened as well that have yet to be accepted.

Will try get the scheduled workflow going.

**Comment by Nekroze** [comment]
doing this means the PR's to `stable` branch are no longer created by one stackholder and thus requiring the review approval of another. Instead the branch protection will need to be changed to require two approvals instead.

**Comment by Nekroze** [comment]
Lets see what happens on Monday.

**Comment by Nekroze** [comment]
The workflow did not trigger this morning. Could be a timezone issue though so I will leave it another 24 hours before looking to change the workflow trigger.

**Comment by Nekroze** [comment]
#331

**Comment by Nekroze** [comment]
failed due to lack of PR message.

**Comment by Nekroze** [comment]
added body to pr script in #336 

next increment needs to close any open prs from this script and user to keep only the latest one open.

**Comment by Nekroze** [comment]
looks like the PR will automatically include new merges to master as they come in so I guess the key is more to not open a new PR if one already exists rather than replace the old one.

**Comment by Nekroze** [comment]
I think it already has an impotent property in effect, no secondary PR was opened last week when the first was not merged. Closing this as done.
