### ISSUE TITLE
Pass DAB_APPS_SELENIUM_TZ to the selenium app container

### ISSUE THREAD

**Issue by nickgerman** [Nekroze/dab#332]
### Please describe the current behaviour

At present dab does not add the TZ envar to the selenium container

### What is suboptimal about the current behaviour

The current behaviour is insufficient because setting the timezone is fun and occasionally required

### Describe the way you think it should behave

DAB_APPS_SELENIUM_TZ should be passed to the selenium container

**Comment by Nekroze** [comment]
Closed by #334
