### ISSUE TITLE
Passthrough of DAB_APPS_<APP_NAME>_<VARIABLES>

### ISSUE THREAD

**Issue by nickgerman** [Nekroze/dab#335]
### Is your feature request related to a problem? Please describe

Dockerhub images can be updated to contain additional configuration environment variables.  Not having to update DAB to support each new variable would be a bonus.

### Describe the solution you'd like

All DAB_APPS_<SERVICE> envars are passed to the service containers, as is without the DAB_APPS_<SERVICE> portion of the envar.

### Describe alternatives you've considered

Specifically add each use case envar to the service definitions in apps

**Comment by Nekroze** [comment]
This would be nice, how do you envisage doing this though? perhaps docker-compose's env file support and we could do a limited dump of `env | grep -E '^DAB_APPS_'`

**Comment by Nekroze** [comment]
Closed by #362
