### ISSUE TITLE
'dab pki destroy' is slow

### ISSUE THREAD

**Issue by tommymcguiver** [Nekroze/dab#342]
### Describe the bug

'dab pki destroy' command is slow.

### To Reproduce
On OSX

1. Run `dab pki destroy`
1. Function takes way to long to complete

### Expected behavior

'dab pki destroy' should takes seconds not minutes. This is due to the large amount of files in my home directory.

It seem that we scan directories for files we want rather than checking in known locations.

### `dab version` output

```
Dab Version: d10a53b9777d72ea081e61a1dc026c358a75d104
Server Version: 18.09.2
Runtimes: runc
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
Architecture: x86_64
```

**Comment by Nekroze** [comment]
I agree, I do not think this is so much of an OSX problem as a design problem, it does indeed scan and therefore depend somewhat on how many files are under your `$HOME`.

We cannot purely check known locations as many browsers store the cert db per profile which has a random ID and thus path, however we can split up the scan into multiple scans of those common locations.

This might slightly increase the best case running time but should greatly reduce the worst case times.

**Comment by tommymcguiver** [comment]
I agree is a design issue. The PKI is managed using the security command on OSX so the pki subcommand is not relevant.

What browsers / disto's are supported?

**Comment by Nekroze** [comment]
I have seen it work on Firefox and Chrome on Linux. Perhaps the key injection could be limited to Linux by default if it only works there at present anyways.

**Comment by tommymcguiver** [comment]
I agree i'll create an issue to resolve that. What should the limited search path's be for finding the certs ? ~/.mozilla/firefox ~/.pki/nssdb.  Don't know if nssdb is a file or a directory. I'm guessing it's a directory.

ref: http://blog.xelnor.net/firefox-systemcerts/

Hard to tell without a linux pc or downloading a VM image.

**Comment by Nekroze** [comment]
Iirc certutil needs the directory not file but yeah we will have to collect some paths that are valid. `~/.pki/` or perhaps something more specific if found should be on the list as I think that is chrome. I cannot remember the Firefox path off the top of my head.
