### ISSUE TITLE
certutil function should only operate on linux machines

### ISSUE THREAD

**Issue by tommymcguiver** [Nekroze/dab#345]
## Change Request

certutil function should only operate on machines with linux hosts. 

### Please describe the current behaviour

certutil runs on all hosts types

### What is suboptimal about the current behaviour

Wasting CPU cycles on hosts other than linux, because it's not supported on other platforms.

**Comment by Nekroze** [comment]
Funny enough I added `DAB_HOST_UNAME` last night for #343 that would be perfect for switching this behaviour.
