### ISSUE TITLE
dab group run doesn't fail fast

### ISSUE THREAD

**Issue by tommymcguiver** [Nekroze/dab#418]
### Describe the bug

The `dab group run $group` command doesn't fail fast. The `dab group run $group` command runs individual `dab repo entrypoint run` commands. If one `dab repo entrypoint run` command in the group fails the subsequent commands continue rather than failing and displaying a message.

This behaviour regressed in this change:
https://github.com/Nekroze/dab/pull/409/files

It makes it rather hard to troubleshoot issues if starting your group provides a lot of output and the error disappears from screen. Failing fast would allow you to see the source of the error immediately and rectify.

**Comment by Nekroze** [comment]
Thanks for the report @tommymcguiver, I did not know but https://linux.die.net/man/1/xargs states that xargs will only fail fast on exit status 255, not any non zero status like a shell.

I will do up a fix and regression test to ensure this does not break again, should have something by tonight.

**Comment by tommymcguiver** [comment]
You could hack 
```
	xargs -I{} sh -c "$depcmd {} || exit 355" <"$configpath"
```
But the output looks ugly and looks like there is an internal issue with DAB. I'm trying to get the exact cause of #409  from @bencollerson to ensure my PR #419 doesn't regress his issue.

**Comment by Nekroze** [comment]
> But the output looks ugly and looks like there is an internal issue with DAB. I'm trying to get the exact cause of #409 from @bencollerson to ensure my PR #419 doesn't regress his issue.

I think that that is the right way to go so we keep the improvement that switching to xargs delivered (but status 255) so we will just need to redo the output by suppressing the xargs output on error. We can even add a section to captain hindsight to suggest common fixes or reasons for this.

```
	xargs -I{} sh -c "$depcmd {} || exit 355" <"$configpath" 2>/dev/null  || fatality "$depcmd exploded"
```

**Comment by tommymcguiver** [comment]
I'm not two fussed on the implementation. In my PR i've added automated testing around:
- Child processes doesn't read parent process input
- It fails fast
- Error message is informative.

**Comment by tommymcguiver** [comment]
> I think that that is the right way to go so we keep the improvement that switching to xargs delivered (but status 255) so we will just need to redo the output by suppressing the xargs output on error. We can even add a section to captain hindsight to suggest common fixes or reasons for this.

I tried the xargs method and it strips the actual error needed to debug the problem. Keeping the for loop and using the fatality method keeps the error text and gives context to the dab child command that failed.
