### ISSUE TITLE
Update Docker Hub Images

### ISSUE THREAD

**Issue by Nekroze** [Nekroze/dab#458]
Manual update required until #454 is implemented and there was a recent change to main and stable branches.

**Comment by Nekroze** [comment]
@slt latest tag is updated, will await for some indication all is well there before updating stable

**Comment by slt** [comment]
Hi @Nekroze, myself, @jumbo-grke and a few others have been using latest without issues and are happy for it to be promoted to stable

**Comment by Nekroze** [comment]
`stable` pushed, any time guys!
