### ISSUE TITLE
Groups should be able to depend on groups

### ISSUE THREAD

**Issue by petranidis** [Nekroze/dab#86]
# Is your feature request related to a problem? Please describe

Single adding only a service each time can be time consuming and can lead to problem for networking in the future

# Describe the solution you'd like

A new feature should be engineered, allowing groups of microservices depend on other groups. This
way the start/stop procedure can be standardised resulting in lower times for network and debugging.

# Describe alternatives you've considered

# Additional context

**Comment by Nekroze** [comment]
at present a group will start its services first, then its repos, and finally its tools. Where in this process do you do you think all group dependencies should be started? At present I am thinking before the services.
